AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Capfile'
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
  TargetRubyVersion: 2.1
Style/WhileUntilModifier:
  MaxLineLength: 120
Style/WhileUntilModifier:
  MaxLineLength: 120
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Rails:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/DotPosition:
  EnforcedStyle: trailing
Style/MultilineHashBraceLayout:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
Style/CharacterLiteral:
  Enabled: false
